# fly.toml app configuration file generated for proj49 on 2023-08-11T03:19:05-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "proj49"
primary_region = "yyz"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
